/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DictationRouteImport } from './routes/dictation'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesHangmanRouteImport } from './routes/games.hangman'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesSnakeRouteImport } from './routes/games.snake'
import { Route as GamesSortRouteImport } from './routes/games.sort'
import { Route as GamesTimeRouteImport } from './routes/games.time'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TeacherClassClassIdRouteImport } from './routes/teacher.class.$classId'
import { Route as TeacherClassClassIdStudentStudentIdRouteImport } from './routes/teacher.class.$classId.student.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationRoute = DictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHangmanRoute = GamesHangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSnakeRoute = GamesSnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSortRoute = GamesSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => GamesRoute,
} as any)
const GamesTimeRoute = GamesTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => GamesRoute,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassClassIdRoute = TeacherClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassClassIdStudentStudentIdRoute =
  TeacherClassClassIdStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => TeacherClassClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dictation': typeof DictationRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games/': typeof GamesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRouteWithChildren
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dictation': typeof DictationRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games': typeof GamesIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRouteWithChildren
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dictation': typeof DictationRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games/': typeof GamesIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRouteWithChildren
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dictation'
    | '/games'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/quiz'
    | '/teacher'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games/'
    | '/teacher/'
    | '/api/auth/$'
    | '/teacher/class/$classId'
    | '/teacher/class/$classId/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dictation'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/quiz'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games'
    | '/teacher'
    | '/api/auth/$'
    | '/teacher/class/$classId'
    | '/teacher/class/$classId/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dictation'
    | '/games'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/quiz'
    | '/teacher'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games/'
    | '/teacher/'
    | '/api/auth/$'
    | '/teacher/class/$classId'
    | '/teacher/class/$classId/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DictationRoute: typeof DictationRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizRoute: typeof QuizRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  ReadIdRoute: typeof ReadIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation': {
      id: '/dictation'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof DictationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/hangman': {
      id: '/games/hangman'
      path: '/hangman'
      fullPath: '/games/hangman'
      preLoaderRoute: typeof GamesHangmanRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/snake': {
      id: '/games/snake'
      path: '/snake'
      fullPath: '/games/snake'
      preLoaderRoute: typeof GamesSnakeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/sort': {
      id: '/games/sort'
      path: '/sort'
      fullPath: '/games/sort'
      preLoaderRoute: typeof GamesSortRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/time': {
      id: '/games/time'
      path: '/time'
      fullPath: '/games/time'
      preLoaderRoute: typeof GamesTimeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class/$classId': {
      id: '/teacher/class/$classId'
      path: '/class/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof TeacherClassClassIdRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/class/$classId/student/$studentId': {
      id: '/teacher/class/$classId/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/teacher/class/$classId/student/$studentId'
      preLoaderRoute: typeof TeacherClassClassIdStudentStudentIdRouteImport
      parentRoute: typeof TeacherClassClassIdRoute
    }
  }
}

interface GamesRouteChildren {
  GamesHangmanRoute: typeof GamesHangmanRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesSnakeRoute: typeof GamesSnakeRoute
  GamesSortRoute: typeof GamesSortRoute
  GamesTimeRoute: typeof GamesTimeRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesHangmanRoute: GamesHangmanRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesSnakeRoute: GamesSnakeRoute,
  GamesSortRoute: GamesSortRoute,
  GamesTimeRoute: GamesTimeRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface TeacherClassClassIdRouteChildren {
  TeacherClassClassIdStudentStudentIdRoute: typeof TeacherClassClassIdStudentStudentIdRoute
}

const TeacherClassClassIdRouteChildren: TeacherClassClassIdRouteChildren = {
  TeacherClassClassIdStudentStudentIdRoute:
    TeacherClassClassIdStudentStudentIdRoute,
}

const TeacherClassClassIdRouteWithChildren =
  TeacherClassClassIdRoute._addFileChildren(TeacherClassClassIdRouteChildren)

interface TeacherRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherClassClassIdRoute: typeof TeacherClassClassIdRouteWithChildren
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherClassClassIdRoute: TeacherClassClassIdRouteWithChildren,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DictationRoute: DictationRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  QuizRoute: QuizRoute,
  TeacherRoute: TeacherRouteWithChildren,
  ReadIdRoute: ReadIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
