/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictationRouteImport } from './routes/dictation'
import { Route as GamesRouteImport } from './routes/games'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesHangmanRouteImport } from './routes/games.hangman'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as GamesSnakeRouteImport } from './routes/games.snake'
import { Route as GamesSortRouteImport } from './routes/games.sort'
import { Route as GamesTimeRouteImport } from './routes/games.time'
import { Route as ReadIdRouteImport } from './routes/read.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationRoute = DictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesHangmanRoute = GamesHangmanRouteImport.update({
  id: '/hangman',
  path: '/hangman',
  getParentRoute: () => GamesRoute,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSnakeRoute = GamesSnakeRouteImport.update({
  id: '/snake',
  path: '/snake',
  getParentRoute: () => GamesRoute,
} as any)
const GamesSortRoute = GamesSortRouteImport.update({
  id: '/sort',
  path: '/sort',
  getParentRoute: () => GamesRoute,
} as any)
const GamesTimeRoute = GamesTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => GamesRoute,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/games': typeof GamesRouteWithChildren
  '/quiz': typeof QuizRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/quiz': typeof QuizRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/games': typeof GamesRouteWithChildren
  '/quiz': typeof QuizRoute
  '/games/hangman': typeof GamesHangmanRoute
  '/games/match': typeof GamesMatchRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sort': typeof GamesSortRoute
  '/games/time': typeof GamesTimeRoute
  '/read/$id': typeof ReadIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dictation'
    | '/games'
    | '/quiz'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dictation'
    | '/quiz'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/dictation'
    | '/games'
    | '/quiz'
    | '/games/hangman'
    | '/games/match'
    | '/games/snake'
    | '/games/sort'
    | '/games/time'
    | '/read/$id'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictationRoute: typeof DictationRoute
  GamesRoute: typeof GamesRouteWithChildren
  QuizRoute: typeof QuizRoute
  ReadIdRoute: typeof ReadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation': {
      id: '/dictation'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof DictationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/hangman': {
      id: '/games/hangman'
      path: '/hangman'
      fullPath: '/games/hangman'
      preLoaderRoute: typeof GamesHangmanRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/match': {
      id: '/games/match'
      path: '/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/snake': {
      id: '/games/snake'
      path: '/snake'
      fullPath: '/games/snake'
      preLoaderRoute: typeof GamesSnakeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/sort': {
      id: '/games/sort'
      path: '/sort'
      fullPath: '/games/sort'
      preLoaderRoute: typeof GamesSortRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/time': {
      id: '/games/time'
      path: '/time'
      fullPath: '/games/time'
      preLoaderRoute: typeof GamesTimeRouteImport
      parentRoute: typeof GamesRoute
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesRouteChildren {
  GamesHangmanRoute: typeof GamesHangmanRoute
  GamesMatchRoute: typeof GamesMatchRoute
  GamesSnakeRoute: typeof GamesSnakeRoute
  GamesSortRoute: typeof GamesSortRoute
  GamesTimeRoute: typeof GamesTimeRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesHangmanRoute: GamesHangmanRoute,
  GamesMatchRoute: GamesMatchRoute,
  GamesSnakeRoute: GamesSnakeRoute,
  GamesSortRoute: GamesSortRoute,
  GamesTimeRoute: GamesTimeRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictationRoute: DictationRoute,
  GamesRoute: GamesRouteWithChildren,
  QuizRoute: QuizRoute,
  ReadIdRoute: ReadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
